import React from 'react';
// @ts-ignore
import pkg from '../../../package.json';

const VERSION = pkg.version;

const Footer = () => (
  <footer className="">
    <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
        <div>
          <h3 className="text-lg font-semibold text-secondary-700 mb-4">About A11YO</h3>
          <p className="text-gray-600 mb-4">
            A11YO helps organizations create compliant accessibility statements that meet international standards and regulations.
          </p>
        </div>
        <div>
          <h3 className="text-lg font-semibold text-secondary-700 mb-4">Contact</h3>
          <p className="text-gray-600 mb-4">
            Have questions about accessibility statements? Get in touch with us.
          </p>
          <a href="mailto:hello@fergflannery.com" className="text-primary-300 hover:text-primary-400">
            hello@fergflannery.com
          </a>
        </div>
        <div>
          <h3 className="text-lg font-semibold text-secondary-700 mb-4">Accessibility</h3>
          <p className="text-gray-600 mb-4">
            This website is committed to making its content accessible to everyone. We strive to meet WCAG 2.2 Level AA standards.
          </p>
          <a href="mailto:hello@fergflannery.com" className="text-primary-300 hover:text-primary-400">
            Report an accessibility issue
          </a>
        </div>
        <div>
          <h3 className="text-lg font-semibold text-secondary-700 mb-4">Support the Developer</h3>
          <p className="text-gray-600 mb-4">
            This platform was created to help make accessibility compliance easier for everyone. If you find it valuable, consider supporting its development.
          </p>
          <a
            href="https://buy.stripe.com/9AQ6oY2hK7AhgtW144"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-primary-300 hover:bg-primary-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-300"
          >
            Support A11YO
          </a>
        </div>
      </div>
      <div className="mt-8 pt-8 border-t border-gray-200">
        <div className="flex flex-col md:flex-row justify-between items-center">
          <p className="text-gray-500">
            © {new Date().getFullYear()} A11YO. All rights reserved.
          </p>
          <div className="flex items-center space-x-4">
            <p className="text-gray-500 mt-4 md:mt-0">
              Generated by <a href="mailto:hello@fergflannery.com" className="text-primary-300 hover:text-primary-400">hello@fergflannery.com</a>
            </p>
            <span className="text-sm text-gray-400">v{VERSION}</span>
          </div>
        </div>
      </div>
    </div>
  </footer>
);

export default Footer; 